# Generated by Django 3.1.2 on 2020-11-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('positif', models.CharField(max_length=50)),
                ('sembuh', models.CharField(max_length=50)),
                ('meninggal', models.CharField(max_length=50)),
                ('dirawat', models.CharField(max_length=50)),
            ],
        ),
    ]
